# Generated by Django 3.2.25 on 2024-07-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flan_uuid', models.UUIDField()),
                ('mombre', models.CharField(max_length=64)),
                ('descripcion', models.TextField()),
                ('imagen_url', models.URLField()),
                ('slug', models.SlugField()),
                ('es_privado', models.BooleanField()),
            ],
        ),
    ]
