# Generated by Django 3.2.25 on 2024-07-04 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flan',
            old_name='mombre',
            new_name='nombre',
        ),
    ]
