# Generated by Django 3.2.25 on 2024-07-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_suscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='precio',
            field=models.FloatField(default=10990),
        ),
    ]
